<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Content' => 'Contenido',
    'Entity' => 'Entity',
    'Entity ID' => 'Entity ID',
    'Parent ID' => 'Parent ID',
    'Status' => 'Estado',
    'Level' => 'Nivel',
    'Created by' => 'Creado por',
    'Updated by' => 'Actualizado por ',
    'Related to' => 'Relacionado a',
    'Url' => 'Url',
    'Created date' => 'Creado el ',
    'Updated date' => 'Modificado el ',
    'View' => 'Ver',
    'Update' => 'Modificar',
    'Delete' => 'Borrar',
    'Reply' => 'Responder',
    'Comments ({0})' => 'Comentarios ({0})',
    'Comment cannot be blank.' => 'El comentario no puede estar vacío.',
    'Comment has not been deleted. Please try again!' => 'El comentario no pudo borrarse. Por favor, trate de nuevo más tarde!',
    'Add a comment...' => 'Agregar comentario ...',
    'Comment' => 'Comentario',
    'Oops, something went wrong. Please try again later.' => 'Oops, something went wrong. Por favor, trate de nuevo más tarde!',
    'The requested page does not exist.' => 'The requested page does not exist.',
    'Comment has been deleted.' => 'El comentario ha sido eliminado.',
    'Comment has been saved.' => 'El comentario fue creado.',
    'Click here to cancel reply.' => 'Click aquí para cancelar.',
    'Comments Management' => 'Administración de Comentarios',
    'Select Status' => 'Seleccionar Estado',
    'Select Author' => 'Seleccionar Autos',
    'Update Comment: {0}' => 'Actulualizar Comentario: {0}',
    'Active' => 'Activo',
    'Deleted' => 'Eliminado',
    'Go Back' => 'Volver',
];
